# Generated by Django 3.0.6 on 2020-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200604_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='medium',
            field=models.CharField(choices=[('E', 'English'), ('B', 'Bangla')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('D', 'Day')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ssc_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
