# Generated by Django 3.0.6 on 2020-06-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200604_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='form_teacher',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
