# Generated by Django 3.0.6 on 2020-06-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_profile_form_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ssc_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
